POST / HTTP/1.1
Host: localhost:8080
Content-Type: text/plain
Accept-Encoding: gzip

https://waka.ru
###
DELETE /api/user/urls HTTP/1.1
Host: localhost:8080
Content-Type: application/json

["53ae9f", "ca8d0d"]

###
GET /ca8d0d HTTP/1.1
Host: localhost:8080
Content-Type: text/plain

###
GET /api/user/urls HTTP/1.1
Host: localhost:8080
Content-Type: text/plain

###

POST /api/shorten HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Accept-Encoding: gzip
Cookie: shortener-user-id=a4ef7735-fc1c-4de9-b7d3-137c6edcb9f2

{
  "url": "https://practicum.yandex.r1222"
}

###

POST /api/shorten/batch HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Accept-Encoding: gzip


[
  {
      "correlation_id": "perviy",
      "original_url": "http://yandex.ru"
  },
  {
      "correlation_id": "vtoroi",
      "original_url": "http://google.com"
  }
]
###

POST /api/shorten/batch HTTP/1.1
Host: localhost:8080
Accept: application/json
Content-Type: application/json
User-Agent: go-resty/2.7.0 (https://github.com/go-resty/resty)

Тело запроса:

[
  {
    "correlation_id":"82368798-54da-420e-b81c-c59ebd0a8e6e",
    "original_url":"http://viaah4dtpj.yandex"},
  {
    "correlation_id":"ada9f403-e65d-4f16-9ea2-6062662a6124",
    "original_url":"http://remrae.net/rrur0od0nl/jk1jgjaifz"
  }
]
